title: best-practices-testing
description: test repo for best practices
template:
  repo: best-practices-testing-template
  name: best-practices-testing
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: pull_request
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: new-issue.md
      - type: getTree
        action_id: isInTree
        recursive: true
      - type: gate
        left: '%actions.isInTree.data.tree%'
        operator: includes
        right: 'path:LICENSE'
        else:
          # help user with proper file name or location
          - type: respond
            with: e-wrong-file-location.md
            data:
              haveFile: ''
              needFile: LICENSE
              editLink: >-
                {{store.repository_url}}/new/{{store.first_pull_headref}}?filename=LICENSE
              fileName: LICENSE
      - type: respond
        with: done.md
